# Generated by Django 5.2.3 on 2025-06-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_fileupload_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filecategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
