# Generated by Django 5.2.3 on 2025-07-02 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_systemuser_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="brts_unit",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.unit"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.systemuser",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="terminal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.terminal",
            ),
        ),
        migrations.AlterField(
            model_name="systemuser",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="terminal",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="ProblemCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "brts_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.unit"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ticket",
            name="problem_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.problemcategory",
            ),
        ),
    ]
