# Generated by Django 5.2.3 on 2025-07-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_ticket_brts_unit_ticket_responsible_ticket_terminal_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="region",
        ),
    ]
