# Generated by Django 5.2.3 on 2025-07-03 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_customer_email_remove_customer_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="terminal",
            name="location",
        ),
        migrations.RemoveField(
            model_name="terminal",
            name="name",
        ),
        migrations.AddField(
            model_name="terminal",
            name="branch_name",
            field=models.CharField(default="Main Branch", max_length=100),
        ),
        migrations.AddField(
            model_name="terminal",
            name="cdm_name",
            field=models.CharField(default="CDM-Default", max_length=100),
        ),
        migrations.AddField(
            model_name="terminal",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.customer",
            ),
        ),
        migrations.AddField(
            model_name="terminal",
            name="model",
            field=models.CharField(default="ModelX", max_length=100),
        ),
        migrations.AddField(
            model_name="terminal",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.region",
            ),
        ),
        migrations.AddField(
            model_name="terminal",
            name="serial_number",
            field=models.CharField(default="SN0000", max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="terminal",
            name="zone",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.zone"
            ),
        ),
    ]
