# Generated by Django 5.2.3 on 2025-07-03 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_terminal_location_remove_terminal_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VersionControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manufacturer", models.CharField(max_length=100)),
                ("template", models.CharField(max_length=100)),
                ("firmware", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.terminal"
                    ),
                ),
            ],
        ),
    ]
