# Generated by Django 5.2.3 on 2025-07-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_versioncontrol"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=50)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to="reports/")),
            ],
        ),
    ]
