# Generated by Django 5.2.3 on 2025-07-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_emailotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("editor", "Editor"),
                    ("viewer", "Viewer"),
                ],
                max_length=20,
            ),
        ),
    ]
