# Generated by Django 5.2.3 on 2025-07-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_ticket_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='region',
        ),
    ]
