# Generated by Django 5.2.3 on 2025-07-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_ticket_comment_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='comment_summary',
        ),
    ]
