# Generated by Django 5.2.3 on 2025-07-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_ticket_comment_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comment_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
