# Generated by Django 5.2.3 on 2025-07-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_ticket_comment_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketComment',
        ),
    ]
